import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('api', {
  parfums: {
    getAll: () => ipcRenderer.invoke('parfum:getAll'),
    create: (data: any) => ipcRenderer.invoke('parfum:create', data),
    update: (id: number, data: any) => ipcRenderer.invoke('parfum:update', { id, data }),
    delete: (id: number) => ipcRenderer.invoke('parfum:delete', id),
    getHistory: (parfumId: number) => ipcRenderer.invoke('parfum:getHistory', parfumId),
    duplicate: (id: number, data?: any) => ipcRenderer.invoke('parfum:duplicate', { id, data }),
    getByBarcode: (barcode: string) => ipcRenderer.invoke('parfum:getByBarcode', barcode),
    getByCategory: (categoryId: number) => ipcRenderer.invoke('parfum:getByCategory', categoryId),
    getByTag: (tagId: number) => ipcRenderer.invoke('parfum:getByTag', tagId),
  },
  categories: {
    getAll: () => ipcRenderer.invoke('category:getAll'),
    create: (data: any) => ipcRenderer.invoke('category:create', data),
    update: (id: number, data: any) => ipcRenderer.invoke('category:update', { id, data }),
    delete: (id: number) => ipcRenderer.invoke('category:delete', id),
  },
  tags: {
    getAll: () => ipcRenderer.invoke('tag:getAll'),
    create: (data: any) => ipcRenderer.invoke('tag:create', data),
    update: (id: number, data: any) => ipcRenderer.invoke('tag:update', { id, data }),
    delete: (id: number) => ipcRenderer.invoke('tag:delete', id),
    getForParfum: (parfumId: number) => ipcRenderer.invoke('tag:getForParfum', parfumId),
    setForParfum: (parfumId: number, tagIds: number[]) => ipcRenderer.invoke('tag:setForParfum', { parfumId, tagIds }),
  },
  fournisseurs: {
    getAll: () => ipcRenderer.invoke('fournisseur:getAll'),
    create: (data: any) => ipcRenderer.invoke('fournisseur:create', data),
    update: (id: number, data: any) => ipcRenderer.invoke('fournisseur:update', { id, data }),
    delete: (id: number) => ipcRenderer.invoke('fournisseur:delete', id),
    comparePrices: (productId: number) => ipcRenderer.invoke('fournisseur:comparePrices', productId),
  },
  clients: {
    getAll: () => ipcRenderer.invoke('client:getAll'),
    create: (data: any) => ipcRenderer.invoke('client:create', data),
    update: (id: number, data: any) => ipcRenderer.invoke('client:update', { id, data }),
    delete: (id: number) => ipcRenderer.invoke('client:delete', id),
  },
  references: {
    getAll: () => ipcRenderer.invoke('reference:getAll'),
    create: (data: any) => ipcRenderer.invoke('reference:create', data),
    update: (id: number, data: any) => ipcRenderer.invoke('reference:update', { id, data }),
    delete: (id: number) => ipcRenderer.invoke('reference:delete', id),
    updatePrice: (id: number, newPrice: number, reason?: string, changedBy?: string) => ipcRenderer.invoke('reference:updatePrice', { id, newPrice, reason, changedBy }),
    setPricePer100g: (id: number, prixPar100g: number) => ipcRenderer.invoke('reference:setPricePer100g', { id, prixPar100g }),
    getPriceHistory: (referenceId: number, limit?: number) => ipcRenderer.invoke('reference:getPriceHistory', { referenceId, limit }),
    getPriceTiers: (referenceId: number) => ipcRenderer.invoke('reference:getPriceTiers', referenceId),
    setPriceTiers: (referenceId: number, tiers: any[]) => ipcRenderer.invoke('reference:setPriceTiers', { referenceId, tiers }),
    getOrderHistory: (referenceId: number) => ipcRenderer.invoke('reference:getOrderHistory', referenceId),
    import: (data: any[]) => ipcRenderer.invoke('reference:import', data),
  },
  stock: {
    getAll: () => ipcRenderer.invoke('stock:getAll'),
    getById: (id: number) => ipcRenderer.invoke('stock:getById', id),
    updateQuantity: (referenceId: number, delta: number, user?: string, reason?: string) => ipcRenderer.invoke('stock:updateQuantity', { referenceId, delta, user, reason }),
    setQuantity: (referenceId: number, quantity: number, user?: string, reason?: string) => ipcRenderer.invoke('stock:setQuantity', { referenceId, quantity, user, reason }),
    updateDetails: (referenceId: number, data: any) => ipcRenderer.invoke('stock:updateDetails', { referenceId, data }),
    reserve: (referenceId: number, quantity: number, user?: string) => ipcRenderer.invoke('stock:reserve', { referenceId, quantity, user }),
    cancelReservation: (referenceId: number, quantity: number, user?: string) => ipcRenderer.invoke('stock:cancelReservation', { referenceId, quantity, user }),
    getMovements: (stockId: number, limit?: number) => ipcRenderer.invoke('stock:getMovements', { stockId, limit }),
    getLowAlerts: () => ipcRenderer.invoke('stock:getLowAlerts'),
    getHighAlerts: () => ipcRenderer.invoke('stock:getHighAlerts'),
    getExpiring: (days?: number) => ipcRenderer.invoke('stock:getExpiring', days),
    predictRupture: (referenceId: number) => ipcRenderer.invoke('stock:predictRupture', referenceId),
  },
  warehouses: {
    getAll: () => ipcRenderer.invoke('warehouse:getAll'),
    getById: (id: number) => ipcRenderer.invoke('warehouse:getById', id),
    create: (data: any) => ipcRenderer.invoke('warehouse:create', data),
    update: (id: number, data: any) => ipcRenderer.invoke('warehouse:update', { id, data }),
    delete: (id: number) => ipcRenderer.invoke('warehouse:delete', id),
  },
  inventory: {
    getAll: () => ipcRenderer.invoke('inventory:getAll'),
    getById: (id: number) => ipcRenderer.invoke('inventory:getById', id),
    create: (data: any) => ipcRenderer.invoke('inventory:create', data),
    start: (id: number, user?: string) => ipcRenderer.invoke('inventory:start', { id, user }),
    complete: (id: number, user?: string) => ipcRenderer.invoke('inventory:complete', { id, user }),
    cancel: (id: number, user?: string) => ipcRenderer.invoke('inventory:cancel', { id, user }),
    updateLine: (inventoryId: number, stockId: number, countedQty: number, notes?: string, user?: string) => 
      ipcRenderer.invoke('inventory:updateLine', { inventoryId, stockId, countedQty, notes, user }),
    getReport: (id: number) => ipcRenderer.invoke('inventory:getReport', id),
    delete: (id: number) => ipcRenderer.invoke('inventory:delete', id),
    findByBarcode: (barcode: string) => ipcRenderer.invoke('inventory:findByBarcode', barcode),
  },
  uploadImage: (formData: FormData) => ipcRenderer.invoke('upload:image', formData),
});
